[options]
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
db_name = ai_pf_db_clean
addons_path = /opt/odoo/odoo/addons,/opt/odoo/addons,/opt/odoo/addons/queue

; AI & Performance Upgrades
server_wide_modules = base,web,queue_job
workers = 0

max_cron_threads = 1

proxy_mode = True
longpolling_port = 8072
gevent_port = 8072
